# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import judger_pb2 as judger__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in judger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JudgeCoordinatorStub(object):
    """The backend server implements this interface, and the workers call it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportSubmitVerdict = channel.unary_unary(
                '/yukticode.judger.JudgeCoordinator/ReportSubmitVerdict',
                request_serializer=judger__pb2.SubmitVerdictRequest.SerializeToString,
                response_deserializer=judger__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.ReportRunVerdict = channel.unary_unary(
                '/yukticode.judger.JudgeCoordinator/ReportRunVerdict',
                request_serializer=judger__pb2.RunVerdictRequest.SerializeToString,
                response_deserializer=judger__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.StreamBatchRunVerdict = channel.stream_unary(
                '/yukticode.judger.JudgeCoordinator/StreamBatchRunVerdict',
                request_serializer=judger__pb2.RunVerdictRequest.SerializeToString,
                response_deserializer=judger__pb2.ReportResponse.FromString,
                _registered_method=True)


class JudgeCoordinatorServicer(object):
    """The backend server implements this interface, and the workers call it.
    """

    def ReportSubmitVerdict(self, request, context):
        """1. Standard Code Submission (Unary RPC)
        One request from the worker, one response from the backend.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportRunVerdict(self, request, context):
        """2. Single Custom Run (Unary RPC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBatchRunVerdict(self, request_iterator, context):
        """3. Batch Custom Run (Client-Streaming RPC)
        The worker opens a single persistent HTTP/2 connection and streams 
        RunVerdictRequest messages one by one as each test case finishes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JudgeCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportSubmitVerdict': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSubmitVerdict,
                    request_deserializer=judger__pb2.SubmitVerdictRequest.FromString,
                    response_serializer=judger__pb2.ReportResponse.SerializeToString,
            ),
            'ReportRunVerdict': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportRunVerdict,
                    request_deserializer=judger__pb2.RunVerdictRequest.FromString,
                    response_serializer=judger__pb2.ReportResponse.SerializeToString,
            ),
            'StreamBatchRunVerdict': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamBatchRunVerdict,
                    request_deserializer=judger__pb2.RunVerdictRequest.FromString,
                    response_serializer=judger__pb2.ReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yukticode.judger.JudgeCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yukticode.judger.JudgeCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JudgeCoordinator(object):
    """The backend server implements this interface, and the workers call it.
    """

    @staticmethod
    def ReportSubmitVerdict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yukticode.judger.JudgeCoordinator/ReportSubmitVerdict',
            judger__pb2.SubmitVerdictRequest.SerializeToString,
            judger__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportRunVerdict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yukticode.judger.JudgeCoordinator/ReportRunVerdict',
            judger__pb2.RunVerdictRequest.SerializeToString,
            judger__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBatchRunVerdict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/yukticode.judger.JudgeCoordinator/StreamBatchRunVerdict',
            judger__pb2.RunVerdictRequest.SerializeToString,
            judger__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
