# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: judger.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'judger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cjudger.proto\x12\x10yukticode.judger\"p\n\x14SubmitVerdictRequest\x12\x15\n\rsubmission_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x03 \x01(\x01\x12\x16\n\x0epeak_memory_mb\x18\x04 \x01(\x01\"\x8b\x01\n\x11RunVerdictRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07std_out\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x01\x12\x16\n\x0epeak_memory_mb\x18\x05 \x01(\x01\x12\x12\n\ntest_index\x18\x06 \x01(\x05\"2\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb0\x02\n\x10JudgeCoordinator\x12_\n\x13ReportSubmitVerdict\x12&.yukticode.judger.SubmitVerdictRequest\x1a .yukticode.judger.ReportResponse\x12Y\n\x10ReportRunVerdict\x12#.yukticode.judger.RunVerdictRequest\x1a .yukticode.judger.ReportResponse\x12`\n\x15StreamBatchRunVerdict\x12#.yukticode.judger.RunVerdictRequest\x1a .yukticode.judger.ReportResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'judger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITVERDICTREQUEST']._serialized_start=34
  _globals['_SUBMITVERDICTREQUEST']._serialized_end=146
  _globals['_RUNVERDICTREQUEST']._serialized_start=149
  _globals['_RUNVERDICTREQUEST']._serialized_end=288
  _globals['_REPORTRESPONSE']._serialized_start=290
  _globals['_REPORTRESPONSE']._serialized_end=340
  _globals['_JUDGECOORDINATOR']._serialized_start=343
  _globals['_JUDGECOORDINATOR']._serialized_end=647
# @@protoc_insertion_point(module_scope)
